---
- name: Configure haproxy community repository [RedHat]
  ansible.builtin.yum_repository:
    name: "{{ haproxy_repo_name }}"
    description: "{{ haproxy_repo_name }}"
    baseurl: "{{ haproxy_repo_community }}"
    gpgcheck: "{{ haproxy_repo_keyring_url != '' }}"
    gpgkey: ["{{ haproxy_repo_keyring_url }}"]
    enabled: true
  when: haproxy_use_community_repo

- name: Install haproxy [RedHat]
  ansible.builtin.dnf:
    name: '{{ haproxy_package_name }}-{{ haproxy_version }}*'
    state: present
    update_cache: true

- name: Get installed version [RedHat]
  ansible.builtin.command: "haproxy -v"
  changed_when: false
  failed_when: false
  register: haproxy_installed_infos

- name: Ensure that haproxy is installed [RedHat]
  ansible.builtin.assert:
    that:
      - haproxy_installed_infos.rc == 0
    fail_msg: "haproxy version {{ haproxy_version }} is not installed"
