---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    haproxy_use_full_version: false
    haproxy_use_community_repo: true
    haproxy_frontend_ssl_enable: true
    haproxy_frontend_ssl_certificates:
      - {src_file_path: "files/willbrid.crt", dest_filename: "server.crt"}
    haproxy_config_defaults:
      - name: "http"
        options:
          - "option httplog"
          - "log global"
          - "timeout client 1m"
          - "timeout server 1m"
          - "timeout connect 10s"
          - "timeout http-keep-alive 2m"
          - "timeout queue 15s"

  tasks:
    - name: Include os-specific vars [RedHat]
      ansible.builtin.include_vars: "vars/redhat.yml"
      when: ansible_os_family == "RedHat"

    - name: Include os-specific vars [Debian]
      ansible.builtin.include_vars: "vars/debian.yml"
      when: ansible_distribution == "Debian"

    - name: Ignore using community repo when ubuntu24
      ansible.builtin.set_fact:
        haproxy_use_community_repo: false
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "24"

    - name: Include os-specific vars (only Ubuntu) [Debian]
      ansible.builtin.include_vars: "vars/ubuntu.yml"
      when: ansible_distribution == "Ubuntu"

    - name: Include willbrid.haproxy_setup
      ansible.builtin.include_role:
        name: "willbrid.haproxy_setup"
