---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    haproxy_version: "2.8.15"

  tasks:
    - name: Include willbrid.haproxy_setup
      ansible.builtin.include_role:
        name: "willbrid.haproxy_setup"
