---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    haproxy_use_full_version: false
    haproxy_use_community_repo: true
    haproxy_frontend_ssl_enable: true
    haproxy_frontend_ssl_certificates:
      - {src_filename: "files/willbrid.crt", dest_filename: "server.crt"}
    haproxy_config_defaults:
      - name: "http"
        custom_options:
          - "mode http"
          - "option httplog"
          - "log global"
          - "timeout client 1m"
          - "timeout server 1m"
          - "timeout connect 10s"
          - "timeout http-keep-alive 2m"
          - "timeout queue 15s"
    haproxy_config_frontends:
      - name: "frontend_site1"
        binds:
          - "*:8000"
        from_default: "http"
        default_backend: "backend_site1"
      - name: "frontend_site2"
        binds:
          - "*:8080"
          - "*:8443"
        from_default: "http"
        default_backend: "backend_site2"
        custom_options:
          - "mode http"
    haproxy_config_backends:
      - name: "backend_site1"
        from_default: "http"
        servers:
          - "server site1-web 127.0.0.1:8081 check"
      - name: "backend_site2"
        from_default: "http"
        custom_options:
          - "balance roundrobin"
        servers:
          - "server site2-web1 127.0.0.1:8084 check"
          - "server site2-web2 127.0.0.1:8085 check"
          - "server site2-web3 127.0.0.1:8086 check"
  tasks:
    - name: Include os-specific vars [RedHat]
      ansible.builtin.include_vars: "vars/redhat.yml"
      when: ansible_os_family == "RedHat"

    - name: Include os-specific vars [Debian]
      ansible.builtin.include_vars: "vars/debian.yml"
      when: ansible_distribution == "Debian"

    - name: Ignore using community repo when ubuntu24
      ansible.builtin.set_fact:
        haproxy_use_community_repo: false
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "24"

    - name: Include os-specific vars (only Ubuntu) [Debian]
      ansible.builtin.include_vars: "vars/ubuntu.yml"
      when: ansible_distribution == "Ubuntu"

    - name: Include willbrid.haproxy_setup
      ansible.builtin.include_role:
        name: "willbrid.haproxy_setup"
